### ISSUE TITLE
todo list after release 0.9 version

### ISSUE THREAD

**Issue by moonming** [apache/incubator-apisix#903]
- [ ] update docker and push to apache in dockerhub
- [x] update luarocks
- [x] update version of APISIX
- [x] add doc for how to compile dashboard
- [x] update apisix website

**Comment by membphis** [comment]
I have updated Luarocks to version 0.9 right now.
